config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: {only_integer: true}
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :restaurant, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Your Favourite Restaurants</h1>
<%= link_to "Add a new restaurant!", new_restaurant_path, class:"btn btn-success m-3" %>

<% @restaurants.each do |restaurant| %></a>
  <h2><%= restaurant.name%></h2>
  <p>Address: <%= restaurant.address %></p>
  <p>Phone Number: <%= restaurant.phone_number %></p>
  <%= link_to 'Check Restaurant', restaurant_path(restaurant), class: "btn btn-primary" %>
<% end %>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category %>
  <%= f.input :phone_number %>
  <%= f.submit "Create", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
    <h4>Location: <%= @restaurant.address %></h4>
    <h4>Phone Number: <%= @restaurant.phone_number %></h4>
    <h4>Cuisine: <%= @restaurant.category %></h4>
    <br>
    <h4>Reviews:</h4>
    <ul class="list">
    <% @restaurant.reviews.each do |review| %>
      <li><%= review.content%> - <%= review.rating %></li>
    <% end %>
    </ul>
      <%= link_to "Add a rating", new_restaurant_review_path(@restaurant), class:"btn btn-primary" %>
      <%= link_to "Homepage", restaurants_path, class:"btn btn-success ml-3" %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Add a review", class: "btn btn-primary" %>
  <% end %>